# conda package recipe

{% set name = "fastaparser" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ".."

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - fastaparser
  requires:
    - pytest

about:
  home: "https://github.com/Kronopt/FastaParser"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE
  summary: "A Python FASTA file Parser and Writer."
  doc_url: https://fastaparser.readthedocs.io/en/latest/
  dev_url: https://github.com/Kronopt/FastaParser

extra:
  maintainers:
    - Kronopt
  recipe-maintainers:
    - Kronopt
