# MkDocs configuration file

site_name: FastaParser
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Usage:
        - 'usage.md'
        - 'usage_representing_fasta.md'
    - Examples: 'examples.md'
    - API Specification:
        - 'api_reader.md'
        - 'api_writer.md'
        - 'api_fastasequence.md'
        - 'api_lettercode.md'
        - 'api_constants.md'
    - Contributing:
        - 'contributing.md'
        - 'contributing_dev_env.md'
    - Authors: 'authors.md'
    - History: 'history.md'
theme: readthedocs
